experiment_name: mnist_hybrid_noise21_high
data:
  dataset: MNIST
  encoding: hybrid
  num_qubits: 12
  num_classes: 2
  batch_size: 8
  num_train_samples: 192
  num_test_samples: 48
  label_subset:
  - 0
  - 1
  num_features: 144
training:
  epochs: 4
  lr: 0.008
  optimizer: Adam
  save_start_epoch: 2
  save_interval: 2
  checkpoint_dir: checkpoints_noise21/mnist_hybrid/noise_high
  checkpoint_prefix: mnist_hybrid_noise21_high
environment:
  backend: GPU
  add_noise: true
  noise:
    depolarizing_p1: 0.0006
    depolarizing_p2: 0.006
