name: QCNN_project
channels:
  - pytorch   # 关键：添加并优先使用 pytorch 官方频道
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  # PyTorch Section: Let Conda find the best CUDA-enabled version
  - pytorch
  - torchvision
  - torchaudio
  # Other QCNN dependencies
  - qiskit
  - qiskit-machine-learning
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - pyyaml