data:
  angle_scale: 3.0
  batch_size: 8
  dataset: MNIST
  downsampled: true
  encoding: angle
  label_subset:
  - 6
  - 7
  num_classes: 2
  num_features: 16
  num_qubits: 16
  num_test_samples: 64
  num_train_samples: 256
environment:
  add_noise: true
  backend: GPU
  noise:
    depolarizing_p1: 0.00015
    depolarizing_p2: 0.0015
experiment_name: mnist_angle_noise263_mid
model:
  conv_depth: 3
training:
  checkpoint_dir: checkpoints_noise263/mnist_angle/noise_mid
  checkpoint_prefix: mnist_angle_noise263_mid
  epochs: 10
  lr: 0.008
  optimizer: Adam
  save_interval: 1
  save_start_epoch: 1
