experiment_name: "fashion_amplitude_full_v1"

data:
  dataset: "FashionMNIST"
  encoding: "amplitude"
  num_qubits: 10           # 与 MNIST 保持一致的较小 qubits
  num_classes: 10
  batch_size: 32
  num_train_samples: 30000
  num_test_samples: 5000

training:
  epochs: 10
  lr: 0.01
  optimizer: "Adam"
  save_start_epoch: 3
  save_interval: 2
  checkpoint_dir: "checkpoints/fashion_amplitude"
  checkpoint_prefix: "fashion_amp"

environment:
  backend: "GPU"
  add_noise: false
