experiment_name: mnist_hybrid_noise_mid_batch1
data:
  dataset: MNIST
  encoding: hybrid
  num_qubits: 12
  num_features: 144
  num_classes: 10
  batch_size: 16
  num_train_samples: 16
  num_test_samples: 16
training:
  epochs: 1
  lr: 0.01
  optimizer: Adam
  save_start_epoch: 1
  save_interval: 1
  checkpoint_dir: checkpoints/profiling/mnist_hybrid_noise_mid_batch1
  checkpoint_prefix: mnist_hybrid_noise_mid_batch1
environment:
  backend: GPU
  add_noise: true
  noise:
    depolarizing_p1: 0.001
    depolarizing_p2: 0.01
