experiment_name: "fashion_hybrid_4x4_patch_run"
data:
  dataset: "FashionMNIST"
  encoding: "hybrid"
  num_qubits: 4
  num_features: 16
  num_classes: 2
  batch_size: 32
  num_train_samples: 256
  num_test_samples: 128
training:
  epochs: 5
  lr: 0.05
  optimizer: "Adam"
environment:
  backend: "CPU"
  add_noise: false