experiment_name: fashion_amplitude_noise_high
data:
  dataset: FashionMNIST
  encoding: amplitude
  num_qubits: 10
  num_classes: 10
  batch_size: 16
  num_train_samples: 8000
  num_test_samples: 1600
training:
  epochs: 6
  lr: 0.01
  optimizer: Adam
  save_start_epoch: 2
  save_interval: 2
  checkpoint_dir: checkpoints_light/fashion_amplitude/noise_high
  checkpoint_prefix: fashion_amplitude_noise_light_high
environment:
  backend: GPU
  add_noise: true
  noise:
    depolarizing_p1: 0.0025
    depolarizing_p2: 0.025
