experiment_name: mnist_angle_noise_low
data:
  dataset: MNIST
  encoding: angle
  num_qubits: 16
  num_classes: 10
  batch_size: 8
  num_train_samples: 6000
  num_test_samples: 1200
  num_features: 16
training:
  epochs: 6
  lr: 0.01
  optimizer: Adam
  save_start_epoch: 2
  save_interval: 2
  checkpoint_dir: checkpoints_light/mnist_angle/noise_low
  checkpoint_prefix: mnist_angle_noise_light_low
environment:
  backend: GPU
  add_noise: true
  noise:
    depolarizing_p1: 0.0003
    depolarizing_p2: 0.003
