experiment_name: fashion_hybrid_noise2_high
data:
  dataset: FashionMNIST
  encoding: hybrid
  num_qubits: 12
  num_classes: 2
  batch_size: 8
  num_train_samples: 3000
  num_test_samples: 600
  label_subset:
  - 0
  - 1
  num_features: 144
training:
  epochs: 10
  lr: 0.01
  optimizer: Adam
  save_start_epoch: 3
  save_interval: 2
  checkpoint_dir: checkpoints_noise2/fashion_hybrid/noise_high
  checkpoint_prefix: fashion_hybrid_noise2_high
environment:
  backend: GPU
  add_noise: true
  noise:
    depolarizing_p1: 0.0015
    depolarizing_p2: 0.015
